sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.073.0
 - dmd-2.072.2
 - dmd-2.071.0
 - ldc-1.0.0
 - ldc-1.1.0-beta6
 - gdc-6.3.0

matrix:
  allow_failures:
   - d: gdc-6.3.0
   - ldc-1.1.0-beta6

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
