sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.077.0
 - dmd-2.076.0
 - ldc-1.5.0
 - ldc-1.4.0
 - gdc

matrix:
  fast_finish: true
  allow_failures:
   - d: gdc

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH --build=unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

