sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.074.0
 - dmd-2.073.2
 - dmd-2.072.2
 - ldc-1.1.0
 - gdc-6.3.0

matrix:
  allow_failures:
   - d: gdc-6.3.0

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH --build=unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

