sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.072.2
 - dmd-2.071.0
 - dmd-2.068.2
 - ldc-1.0.0
 - gdc-5.2.0
 - gdc-4.9.2

matrix:
  allow_failures:
   - d: gdc-4.9.2
   - d: gdc-5.2.0
   - d: dmd-2.068.2

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
