sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.076.0-dirty
 - dmd-2.075.1
 - ldc-1.4.0
 - ldc-1.3.0
 - ldc-1.2.0
 - gdc

matrix:
  fast_finish: true
  allow_failures:
   - d: gdc
   - d: ldc-1.2.0
     os: osx

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH --build=unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

